using System;
using System.Collections.Generic;
using LiteDB;

namespace Stndr;

public sealed class SefariaWorkMetadata
{
    [BsonId]
    public string WorkKey { get; set; } = string.Empty;
    public string WorkKeyNormalized { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string HebrewTitle { get; set; } = string.Empty;
    public List<string> Categories { get; set; } = new();
    public string PrimaryCategory { get; set; } = string.Empty;
    public List<double> OrderPath { get; set; } = new();
    public int SchemaDepth { get; set; }
    public List<string> SectionNames { get; set; } = new();
    public List<string> AddressTypes { get; set; } = new();
    public List<int> Lengths { get; set; } = new();
    public List<string> TitleVariants { get; set; } = new();
    public string SourceMongoId { get; set; } = string.Empty;
}

public sealed class SefariaTextVersionMetadata
{
    [BsonId]
    public string TextVersionKey { get; set; } = string.Empty;
    public string WorkKey { get; set; } = string.Empty;
    public string WorkTitle { get; set; } = string.Empty;
    public string LanguageCode { get; set; } = "en";
    public string ActualLanguageCode { get; set; } = string.Empty;
    public string VersionTitle { get; set; } = string.Empty;
    public string VersionSource { get; set; } = string.Empty;
    public int Priority { get; set; }
    public bool DigitizedBySefaria { get; set; }
    public string JsonFileName { get; set; } = string.Empty;
    public string SourceMongoId { get; set; } = string.Empty;
}

public sealed class SefariaCategoryMetadata
{
    [BsonId]
    public string PathKey { get; set; } = string.Empty;
    public List<string> Path { get; set; } = new();
    public string LastPath { get; set; } = string.Empty;
    public int Depth { get; set; }
    public string SharedTitle { get; set; } = string.Empty;
    public string EnglishDescription { get; set; } = string.Empty;
    public string HebrewDescription { get; set; } = string.Empty;
    public double Order { get; set; }
    public string SourceMongoId { get; set; } = string.Empty;
}

public sealed class SefariaTermMetadata
{
    [BsonId]
    public string TermKey { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    public string Scheme { get; set; } = string.Empty;
    public string Reference { get; set; } = string.Empty;
    public List<string> Titles { get; set; } = new();
    public List<string> Languages { get; set; } = new();
    public int Order { get; set; }
    public string SourceMongoId { get; set; } = string.Empty;
}

public sealed class SefariaTitleLookup
{
    [BsonId]
    public string Id { get; set; } = string.Empty;
    public string NormalizedTitle { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string EntityType { get; set; } = string.Empty;
    public string EntityKey { get; set; } = string.Empty;
    public string WorkKey { get; set; } = string.Empty;
    public string Language { get; set; } = string.Empty;
}

public sealed class SefariaLinkEdgeMetadata
{
    [BsonId]
    public string EdgeKey { get; set; } = string.Empty;
    public string LinkId { get; set; } = string.Empty;
    public string AnchorRef { get; set; } = string.Empty;
    public string TargetRef { get; set; } = string.Empty;
    public List<string> AnchorExpandedRefs { get; set; } = new();
    public List<string> TargetExpandedRefs { get; set; } = new();
    public string LinkType { get; set; } = string.Empty;
    public bool AutoGenerated { get; set; }
    public string GeneratedBy { get; set; } = string.Empty;
    public string SourceTextOid { get; set; } = string.Empty;
}

public sealed class SefariaTopicLinkMetadata
{
    [BsonId]
    public string LinkKey { get; set; } = string.Empty;
    public string TopicFrom { get; set; } = string.Empty;
    public string TopicTo { get; set; } = string.Empty;
    public string LinkClass { get; set; } = string.Empty;
    public string LinkType { get; set; } = string.Empty;
    public string DataSource { get; set; } = string.Empty;
    public List<string> ExpandedRefs { get; set; } = new();
}

public sealed class SefariaMetadataIngestionRecord
{
    [BsonId]
    public string Id { get; set; } = "latest";
    public DateTime IngestedAtUtc { get; set; }
    public string DumpFilePath { get; set; } = string.Empty;
    public string DumpFileName { get; set; } = string.Empty;
    public long DumpFileBytes { get; set; }
    public int Works { get; set; }
    public int Versions { get; set; }
    public int Categories { get; set; }
    public int Terms { get; set; }
    public int LinkEdges { get; set; }
    public int TopicLinks { get; set; }
}
